"use strict";

// const getData = async function () {
//   let url = "http://127.0.0.1:8000/";
//   const res = await fetch(url);
//   const data = await res.json();
//   console.log(data);
// };

// getData();
const contentLeft1 = document.querySelector(".row10");
const contentRight1 = document.querySelector(".row11");
const contentLeft2 = document.querySelector(".row20");
const contentRight2 = document.querySelector(".row21");
const contentLeft3 = document.querySelector(".row30");
const contentRight3 = document.querySelector(".row31");
const contentLeft4 = document.querySelector(".row40");
const contentRight4 = document.querySelector(".row41");
const contentLeft5 = document.querySelector(".row50");
const contentRight5 = document.querySelector(".row51");
const contentLeft6 = document.querySelector(".row60");
const contentRight6 = document.querySelector(".row61");
const contentLeft7 = document.querySelector(".row70");
const contentRight7 = document.querySelector(".row71");
const contentLeft8 = document.querySelector(".row80");
const contentRight8 = document.querySelector(".row81");
const contentLeft9 = document.querySelector(".row90");
const contentRight9 = document.querySelector(".row91");
const contentLeft10 = document.querySelector(".row100");
const contentRight10 = document.querySelector(".row101");
const contentLeft11 = document.querySelector(".row110");
const contentRight11 = document.querySelector(".row111");
const contentLeft12 = document.querySelector(".row120");
const contentRight12 = document.querySelector(".row121");
const contentLeft13 = document.querySelector(".row130");
const contentRight13 = document.querySelector(".row131");
const contentLeft14 = document.querySelector(".row140");
const contentRight14 = document.querySelector(".row141");

const getContent = async function () {
  let url = "http://127.0.0.1:8000/content";
  const res = await fetch(url);
  const data = await res.json();
  console.log(data);
  contentLeft1.textContent = data[0][0];
  contentRight1.textContent = data[0][1];
  contentLeft2.textContent = data[1][0];
  contentRight2.textContent = data[1][1];
  contentLeft3.textContent = data[2][0];
  contentRight3.textContent = data[2][1];
  contentLeft4.textContent = data[3][0];
  contentRight4.textContent = data[3][1];
  contentLeft5.textContent = data[4][0];
  contentRight5.textContent = data[4][1];
  contentLeft6.textContent = data[5][0];
  contentRight6.textContent = data[5][1];
  contentLeft7.textContent = data[6][0];
  contentRight7.textContent = data[6][1];
  contentLeft8.textContent = data[7][0];
  contentRight8.textContent = data[7][1];
  contentLeft9.textContent = data[8][0];
  contentRight9.textContent = data[8][1];
  contentLeft10.textContent = data[9][0];
  contentRight10.textContent = data[9][1];
  contentLeft11.textContent = data[10][0];
  contentRight11.textContent = data[10][1];
  contentLeft12.textContent = data[11][0];
  contentRight12.textContent = data[11][1];
  contentLeft13.textContent = data[12][0];
  contentRight13.textContent = data[12][1];
  contentLeft14.textContent = data[13][0];
  contentRight14.textContent = data[13][1];
  return null;
};

getContent();
